### ISSUE TITLE
Notification defaults

### ISSUE THREAD

**Issue by ribanez7** [sleede/wupee#7] opened 2017-02-20 20:27 UTC
Hi Sleede team, I've been working these days with wupee on a project, and ended up with a special need:
When a new **notification_type** is generated, I think it's useful to be able to assign a default_behavior to this one (corresponding with the enum **value**, on the **notification_type_configuration**).
I've solved it on my project by adding the column default_behavior, which has the default value of 0 on the database. Then, modifying the after_create callback of the receiver, you can customize it very easily, because it is very handy to be able to configure notifications defaults. Maybe you want a notification to be initialy just via notification only, or just via email, and leave then the freedom to the user to reconfigure it.

So now my notification_types has the column default_behavior, and the callback I'm using is the following one:

```ruby
Wupee::NotificationType.find_each do |notification_type|
  Wupee::NotificationTypeConfiguration.create! do |config|
    config.notification_type_id = notification_type.id
    config.receiver = self
    config.value = notification_type.default_behavior
  end
end
```

Now the generator should accept an option like

```shell
rails g wupee:notification_type user_has_been_created DEFAULT=email
```

This is just an idea, of course, feel free to reject it :)
Thanks!

P.S.: Are you going to update the version?

**Comment by nflorentin** [comment] 2017-02-21 08:36
Hi!

we're glad to hear that your are using wupee in a project ! Thanks for your interest.

Your need is reinforcing my decision to take out the "configuration part" (all Wupee::NotificationTypeConfiguration stuff) from the gem. It is already in the branch `remove-notif-config` and I published a new version `2.0.0.beta1` with thoses changes.

As I can see after using the gem in many projects over months, each app has very different needs in term of "configuration" of the notifications. Some have no need for configuration, some have very particular ones. The problem is that I often had to reopen classes to override default behaviour of the gem or skip callbacks and adding others and I was feeling that something was wrong. And your need is another example of particular need and it'd be very easy to meet it without modifying the gem if the configurations were out of the gem.

You can see the updated [README](https://github.com/sleede/wupee/tree/remove-notif-config) to have more information.
Don't worry, customization is still possible, see documentation of [wupee.rb initializer](https://github.com/sleede/wupee/tree/remove-notif-config#initializer)

I think migrating from version 1.1.4 to 2.0.0 will be quite easy as there is not much code removed.

If you have any questions, feel free to contact me!

**Comment by ribanez7** [comment] 2017-02-22 17:01
Hi Nicolas,

Yes, I didn't like the lots of notification_type_configurations generated. So just checked out the branch you're working on, and will do some test on my app tomorrow.

However, I'm thinking now on how to let the users configure their preferences without that table, have you faced this use case with the new version?
Two simple join tables? like emails_wanted and notifications_wanted? I don't know if I like it too much, regardless it would be a fast query.

What would be your approach?

**Comment by nflorentin** [comment] 2017-02-23 11:16
Hi Rubén !

I think you will still need a join table between users and notification_types in you want to provide a way for yours users to configure their preferences. Two join tables is another possibility and I think it is even more flexible than one. I don't known if there is many others possibilities.

The goal of the new version is to let the app decide how the users will configure their preferences, in a majority of cases I don't need the fine grain flexibility provided by NotificationTypeConfigurations. So in my case the plan is: upgrade to new version (without NotificationTypeConfigurations) seamlessly as I don't need them. And in the only app which currently use NotificationTypeConfigurations, I'll have to extract NotificationTypeConfiguration logic from the gem  and implements it in the app, which would not be very difficult.

**Comment by ribanez7** [comment] 2017-02-23 14:55
Perfect, I will finally get attached with your last version of the gem and 2 models to control it fast, with the proper indexes:

```ruby
# uncomment and implement your logic here to avoid/permit email sending to your users
# leave it commented if you always want your users received emails
Wupee.email_sending_rule = proc do |receiver, notification_type|
  # logic goes here, returning a boolean
  WantsEmail.where(
    user_id: receiver.id,
    notification_type_id: notification_type.id
  ).exists?
end

# uncomment and implement your logic here to avoid/permit email sending to your users
# leave it commented if you always want your users received notifications
Wupee.notification_sending_rule = proc do |receiver, notification_type|
  #   # logic goes here, returning a boolean
  WantsNotification.where(
    user_id: receiver.id,
    notification_type_id: notification_type.id
  ).exists?
end

```

Easy to query, and also to customize.
Thanks for the advices, and waiting for this final v2 ;)

**Comment by nflorentin** [comment] 2017-02-23 16:22
I'm glad I could help. I think we can close the issue.

I'll be testing this version in a new app and therefore release a v2 soon.

Again, thanks for you interest!

**Closed as completed by nflorentin** 2017-02-23 16:22 UTC

**Comment by tommyalvarez** [comment] 2018-08-16 18:39
@ribanez7 I know this is an old issue, but i'm starting to use version 1.1.4 of the gem (v2 is beta yet) and i noticed that i need to run a rake task that creates many NotificationTypeConfiguration for each receiver-notification_type. Is that right? What happens if a new user is created? Do i need to re run the rake task ? Or i should add a callback to the user model to generate a default NotificationTypeConfiguration ?
